[tool.commitizen]
name = "cz_conventional_commits"
version = "1.1.1"
version_files = [
    "project.clj:defproject",
    ".cz.toml:version",
    "VERSION",
    "Dockerfile:NS_SORT_VERSION"
]
tag_format = "v$version"
