[tool.commitizen]
name = "cz_conventional_commits"
version = "1.1.1"
version_files = [
    "project.clj:defproject",
    ".cz.toml:version",
    "VERSION",
    "Dockerfile:NS_SORT_VERSION",
    ".pre-commit-hooks.yaml:ns-sort"
]
tag_format = "v$version"
